In [17]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

from torch.optim import Adam

class test(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, 16),
            
        )

In [26]:
W = torch.tensor([[1, 2, 9],[4, -2, 0], [3, 6, -2]], dtype=torch.float32)
x = torch.tensor([[1.0, 2.2, 0], [-1.9, 2.1, 8]], dtype=torch.float32)
print(x@W)
y = x@W
batch_size, p_size = y.shape
l = nn.LayerNorm(p_size)
l(y)

tensor([[  9.8000,  -2.4000,   9.0000],
        [ 30.5000,  40.0000, -33.1000]])


tensor([[ 0.7777, -1.4118,  0.6341],
        [ 0.5557,  0.8484, -1.4041]], grad_fn=<NativeLayerNormBackward0>)

In [15]:
(x[0] - x[0].mean()) / (x[0].var()) ** 0.5

tensor([-0.0605,  1.0289, -0.9684])

In [13]:
for param in l.parameters():
    print(param.data)

tensor([1., 1., 1.])
tensor([0., 0., 0.])


In [67]:
a = torch.tensor([[[1,2,4]]])
b = torch.tensor([[[4,1,5]]])
c = torch.tensor([[[8,8,8]]])
d = torch.tensor([[[9,9,9]]])
torch.concatenate((a, b, c), dim=1)
stacked1 = torch.stack((a,b), dim=0)
stacked2 = torch.stack((c,d), dim=0)
s2 = torch.stack((stacked1, stacked2), dim=0)
torch.cat((s2, stacked2.unsqueeze(dim=0)), dim=0).shape

torch.Size([3, 2, 1, 1, 3])

In [73]:
a[0][0][0].numpy().reshape(-1)[0]

1

In [83]:
l = nn.Linear(2, 16)
y = l(torch.tensor([1,5.0]))
loss = torch.mean(y)
loss.backward()

In [85]:
l.weight.grad.shape

torch.Size([16, 2])

In [79]:
stacked1[1:]

torch.Size([1, 1, 1, 3])

In [32]:
bs = 5
q = torch.rand((bs, 1))
t = torch.rand((bs, 1))

l = nn.Linear(1, 1)
q = l(q)

q1 = torch.rand((bs +4, 1))
t1 = torch.rand((bs +4, 1))

stacked = torch.stack((q, t), dim=1)
stacked1 = torch.stack((q1, t1), dim=1)

ds = torch.cat((stacked, stacked1), dim=0)
print(ds.shape)
X = ds[:, 0]
y = ds[:, 1]
print(X.shape)

train_loader = DataLoader(list(zip(X, y)), batch_size=5, shuffle=True)
for x_batch, y_batch in train_loader:
    print(x_batch)
    x_batch


torch.Size([14, 2, 1])
torch.Size([14, 1])
tensor([[ 0.5102],
        [-0.0496],
        [ 0.6776],
        [ 0.1651],
        [ 0.3562]], grad_fn=<StackBackward0>)
tensor([[-0.2406],
        [ 0.6292],
        [-0.2333],
        [ 0.9126],
        [ 0.4976]], grad_fn=<StackBackward0>)
tensor([[-0.4284],
        [ 0.1172],
        [-0.4580],
        [ 0.4414]], grad_fn=<StackBackward0>)
